//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Extensions.ApolloFederation.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FederationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FederationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Extensions.ApolloFederation.Properties.FederationResources", typeof(FederationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ThrowHelper_FieldSet_HasInvalidFormat {
            get {
                return ResourceManager.GetString("ThrowHelper_FieldSet_HasInvalidFormat", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_FieldSet_CannotParseValue {
            get {
                return ResourceManager.GetString("ThrowHelper_FieldSet_CannotParseValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Key_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Key_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_External_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_External_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Provides_Field_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Provides_Field_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Provides_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Provides_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Requires_Field_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Requires_Field_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Requires_FieldSet_CannotBeEmpty {
            get {
                return ResourceManager.GetString("ThrowHelper_Requires_FieldSet_CannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Entities_Representation_Typename_Missing {
            get {
                return ResourceManager.GetString("ThrowHelper_Entities_Representation_Typename_Missing", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Entities_Representation_Typename_Invalid {
            get {
                return ResourceManager.GetString("ThrowHelper_Entities_Representation_Typename_Invalid", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Entities_Representation_Entity_NotFound {
            get {
                return ResourceManager.GetString("ThrowHelper_Entities_Representation_Entity_NotFound", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Entities_Representation_Resolver_Error {
            get {
                return ResourceManager.GetString("ThrowHelper_Entities_Representation_Resolver_Error", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_Directive_Field_NotFound {
            get {
                return ResourceManager.GetString("ThrowHelper_Directive_Field_NotFound", resourceCulture);
            }
        }
    }
}
