name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
    - name: Build
      run: dotnet build -c release
    - name: Test
      run: dotnet test -c release
    - name: Pack
      run: dotnet pack -c release -o dist
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: dist/*
